scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.50
    upper_threshold: .inf
    lower_replacement_value: 0.0
    upper_replacement_value: .inf
- name: interpolation
  type: laser_filters/InterpolationFilter
